theme: jekyll-theme-minimal
title: ADA Template Website
description: A template website for ADA
show_downloads: True
navigation:
  - title: Cross-species analysis of Alzheimerâ€™s pathology
    url: /
  - title: Example
    url: example
