theme: jekyll-theme-minimal

title: "Cross-species analysis of Alzheimerâ€™s pathology"
description: "Assessing the relevance of the TgCRND8 mouse model using Xenium spatial transcriptomics."

url: "https://epfl-ada.github.io"
baseurl: "/ada-2025-website-sharknut"

show_downloads: false 

navigation:
  - title: Home
    url: /
